# Perfil NoSQL para Persistencia C1
spring.application.name=app
server.port=8081

# Configuracion del motor y persistencia
app.tree-strategy=custom
app.storage=mongo

# Configuracion MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=proyecto_final_arboles