spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=proyecto_final_arboles
