app.storage=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/progra3db
spring.datasource.username=progra3
spring.datasource.password=progra3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration