spring.application.name=app
server.port=8081

# Configuracion del motor y persistencia
# Estrategias disponibles:
# app.tree-strategy=custom
# app.tree-strategy=collections
app.tree-strategy=collections

# Almacenamientos disponibles:
# app.storage=mongo
# app.storage=memory
# app.storage=postgres
app.storage=postgres

spring.profiles.active=postgres

